name: Publish Blog Article

on:
  workflow_dispatch:
    inputs:
      payload:
        description: "JSON payload from webhook"
        required: true

permissions:
  contents: write

jobs:
  publish-article:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - name: Save payload
        run: node -e "require('fs').writeFileSync('payload.json', process.env.PAYLOAD)"
        env:
          PAYLOAD: ${{ github.event.inputs.payload }}

      - name: Write blog posts
        run: |
          node - <<'EOF'
          const fs = require('fs');
          const path = require('path');

          const payload = JSON.parse(fs.readFileSync('payload.json', 'utf8'));

          for (const article of payload.data.articles) {
            // folder and file name
            const folder = path.join('apps', 'www', 'content', 'blog');
            fs.mkdirSync(folder, { recursive: true });
            const filePath = path.join(folder, `${article.slug}.mdx`);

            // build front-matter using YAML.stringify for safer escaping
            const yaml = require('js-yaml');
            
            const frontMatter = {
              title: article.title,
              description: article.meta_description,
              image: article.image_url,
              author: "Dillion Verma",
              tags: article.tags || [],
              publishedOn: article.created_at,
              featured: true
            };
            
            const fm = '---\n' + yaml.dump(frontMatter) + '---\n';

            // write file with front-matter + markdown content
            fs.writeFileSync(filePath, fm + article.content_markdown);
          }
          EOF

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add blog article from webhook" || echo "No changes"
          git push
